version: '3'
services:
  mongo:
    image: bitnami/mongodb:latest
    container_name: 'mongodb'
    ports:
      - 27017:27017

  searx:
    image: wonderfall/searx
    ports:
      - 8888:8888

  zookeeper:
    image: zookeeper:latest
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${DOCKER_HOST_IP}
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://${DOCKER_HOST_IP}:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      #KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "DiscoveredDomains:1:1,ClassifiedDomains:10:1,ScrapedPages:1:1,CrawledDomains:1:1"

networks:
  default:
    external:
      name: environment-network