version: '3'
services:
  web_discovery:
    build: ./web_discovery
    container_name: 'web_discovery'
    environment:
      KAFKA_BROKER_URL: kafka:9092
      TOPIC_OUTPUT: 'DiscoveredDomains'
      MESSAGES_PER_SECOND: 1000
      SEED: './data/products_seed.txt'
      NUMBER_RESULT_PAGES: 3
      SEARX_ADDRESS: 'http://searx:8888'
      MONGODB_ADDRESS: "mongodb:27017"
      DATABASE: 'DiscoveredDomains'
    external_links:
      - mongo
    volumes:
      - ./web_discovery/data:/data
      - ./web_discovery/src:/src

  classifier:
    build: ./classifier
    container_name: 'classifier'
    environment:
      KAFKA_BROKER_URL: 'kafka:9092'
      TOPIC_INPUT: 'DiscoveredDomains'
      TOPIC_OUTPUT: 'ClassifiedDomains'
      TIMEOUT_POLLING_MS: 10
      MAX_RECORD_POLLING: 5
      MESSAGES_PER_SECOND: 1000
      TRAINING_SET: './data/training_set.csv'
      TRAINING_PARQUET: './data/training_set.snappy.parquet'
      MODEL: './model/classifier.sav'
      MONGODB_ADDRESS: "mongodb:27017"
      DATABASE: 'ClassifiedDomains'
    external_links:
      - mongo
    volumes:
      - ./classifier/data:/data
      - ./classifier/model:/model
      - ./classifier/src:/src

  crawler_1:
    build: ./crawler
    container_name: 'crawler-1'
    environment:
      KAFKA_BROKER_URL: 'kafka:9092'
      CONSUMER_GROUP: 'crawlers'
      TOPIC_INPUT: 'ClassifiedDomains'
      TOPIC_OUTPUT: 'ScrapedPages'
      TIMEOUT_POLLING_MS: 10
      MAX_RECORD_POLLING: 5
      MESSAGES_PER_SECOND: 1000
      DEPTH_LIMIT: 8
      DOWLOAND_DELAY: 0.3
      CLOSESPIDER_PAGECOUNT: 25
      AUTOTHROTTLE_ENABLE: 'true'
      AUTOTHROTTLE_TARGET_CONCURRENCY: 10
      TIMEOUT_CRAWLER: 180
      TIMEOUT_DOWNLOAD: '5'
      MONGODB_ADDRESS: "mongodb:27017"
      DATABASE: 'CrawledPages'
    volumes:
      - ./crawler/src:/src
    external_links:
      - mongo

  crawler_2:
    build: ./crawler
    container_name: 'crawler-2'
    environment:
      KAFKA_BROKER_URL: 'kafka:9092'
      CONSUMER_GROUP: 'crawlers'
      TOPIC_INPUT: 'ClassifiedDomains'
      TOPIC_OUTPUT: 'ScrapedPages'
      TIMEOUT_POLLING_MS: 10
      MAX_RECORD_POLLING: 5
      MESSAGES_PER_SECOND: 1000
      DEPTH_LIMIT: 8
      DOWLOAND_DELAY: 0.3
      CLOSESPIDER_PAGECOUNT: 25
      AUTOTHROTTLE_ENABLE: 'true'
      AUTOTHROTTLE_TARGET_CONCURRENCY: 10
      TIMEOUT_CRAWLER: 180
      TIMEOUT_DOWNLOAD: '5'
      MONGODB_ADDRESS: "mongodb:27017"
      DATABASE: 'CrawledPages'
    volumes:
      - ./crawler/src:/src
    external_links:
      - mongo

  crawler_3:
    build: ./crawler
    container_name: 'crawler-3'
    environment:
      KAFKA_BROKER_URL: 'kafka:9092'
      CONSUMER_GROUP: 'crawlers'
      TOPIC_INPUT: 'ClassifiedDomains'
      TOPIC_OUTPUT: 'ScrapedPages'
      TIMEOUT_POLLING_MS: 10
      MAX_RECORD_POLLING: 5
      MESSAGES_PER_SECOND: 1000
      DEPTH_LIMIT: 8
      DOWLOAND_DELAY: 0.3
      CLOSESPIDER_PAGECOUNT: 25
      AUTOTHROTTLE_ENABLE: 'true'
      AUTOTHROTTLE_TARGET_CONCURRENCY: 10
      TIMEOUT_CRAWLER: 180
      TIMEOUT_DOWNLOAD: '5'
      MONGODB_ADDRESS: "mongodb:27017"
      DATABASE: 'CrawledPages'
    volumes:
      - ./crawler/src:/src
    external_links:
      - mongo

  crawler_4:
    build: ./crawler
    container_name: 'crawler-4'
    environment:
      KAFKA_BROKER_URL: 'kafka:9092'
      CONSUMER_GROUP: 'crawlers'
      TOPIC_INPUT: 'ClassifiedDomains'
      TOPIC_OUTPUT: 'ScrapedPages'
      TIMEOUT_POLLING_MS: 10
      MAX_RECORD_POLLING: 5
      MESSAGES_PER_SECOND: 1000
      DEPTH_LIMIT: 8
      DOWLOAND_DELAY: 0.3
      CLOSESPIDER_PAGECOUNT: 25
      AUTOTHROTTLE_ENABLE: 'true'
      AUTOTHROTTLE_TARGET_CONCURRENCY: 10
      TIMEOUT_CRAWLER: 180
      TIMEOUT_DOWNLOAD: '5'
      MONGODB_ADDRESS: "mongodb:27017"
      DATABASE: 'CrawledPages'
    volumes:
      - ./crawler/src:/src
    external_links:
      - mongo

  crawler_5:
    build: ./crawler
    container_name: 'crawler-5'
    environment:
      KAFKA_BROKER_URL: 'kafka:9092'
      CONSUMER_GROUP: 'crawlers'
      TOPIC_INPUT: 'ClassifiedDomains'
      TOPIC_OUTPUT: 'ScrapedPages'
      TIMEOUT_POLLING_MS: 10
      MAX_RECORD_POLLING: 5
      MESSAGES_PER_SECOND: 1000
      DEPTH_LIMIT: 8
      DOWLOAND_DELAY: 0.3
      CLOSESPIDER_PAGECOUNT: 25
      AUTOTHROTTLE_ENABLE: 'true'
      AUTOTHROTTLE_TARGET_CONCURRENCY: 10
      TIMEOUT_CRAWLER: 180
      TIMEOUT_DOWNLOAD: '5'
      MONGODB_ADDRESS: "mongodb:27017"
      DATABASE: 'CrawledPages'
    volumes:
      - ./crawler/src:/src
    external_links:
      - mongo

  crawler_6:
    build: ./crawler
    container_name: 'crawler-6'
    environment:
      KAFKA_BROKER_URL: 'kafka:9092'
      CONSUMER_GROUP: 'crawlers'
      TOPIC_INPUT: 'ClassifiedDomains'
      TOPIC_OUTPUT: 'ScrapedPages'
      TIMEOUT_POLLING_MS: 10
      MAX_RECORD_POLLING: 5
      MESSAGES_PER_SECOND: 1000
      DEPTH_LIMIT: 8
      DOWLOAND_DELAY: 0.3
      CLOSESPIDER_PAGECOUNT: 25
      AUTOTHROTTLE_ENABLE: 'true'
      AUTOTHROTTLE_TARGET_CONCURRENCY: 10
      TIMEOUT_CRAWLER: 180
      TIMEOUT_DOWNLOAD: '5'
      MONGODB_ADDRESS: "mongodb:27017"
      DATABASE: 'CrawledPages'
    volumes:
      - ./crawler/src:/src
    external_links:
      - mongo

  crawler_7:
    build: ./crawler
    container_name: 'crawler-7'
    environment:
      KAFKA_BROKER_URL: 'kafka:9092'
      CONSUMER_GROUP: 'crawlers'
      TOPIC_INPUT: 'ClassifiedDomains'
      TOPIC_OUTPUT: 'ScrapedPages'
      TIMEOUT_POLLING_MS: 10
      MAX_RECORD_POLLING: 5
      MESSAGES_PER_SECOND: 1000
      DEPTH_LIMIT: 8
      DOWLOAND_DELAY: 0.3
      CLOSESPIDER_PAGECOUNT: 25
      AUTOTHROTTLE_ENABLE: 'true'
      AUTOTHROTTLE_TARGET_CONCURRENCY: 10
      TIMEOUT_CRAWLER: 180
      TIMEOUT_DOWNLOAD: '5'
      MONGODB_ADDRESS: "mongodb:27017"
      DATABASE: 'CrawledPages'
    volumes:
      - ./crawler/src:/src
    external_links:
      - mongo

  crawler_8:
    build: ./crawler
    container_name: 'crawler-8'
    environment:
      KAFKA_BROKER_URL: 'kafka:9092'
      CONSUMER_GROUP: 'crawlers'
      TOPIC_INPUT: 'ClassifiedDomains'
      TOPIC_OUTPUT: 'ScrapedPages'
      TIMEOUT_POLLING_MS: 10
      MAX_RECORD_POLLING: 5
      MESSAGES_PER_SECOND: 1000
      DEPTH_LIMIT: 8
      DOWLOAND_DELAY: 0.3
      CLOSESPIDER_PAGECOUNT: 25
      AUTOTHROTTLE_ENABLE: 'true'
      AUTOTHROTTLE_TARGET_CONCURRENCY: 10
      TIMEOUT_CRAWLER: 180
      TIMEOUT_DOWNLOAD: '5'
      MONGODB_ADDRESS: "mongodb:27017"
      DATABASE: 'CrawledPages'
    volumes:
      - ./crawler/src:/src
    external_links:
      - mongo

  crawler_9:
    build: ./crawler
    container_name: 'crawler-9'
    environment:
      KAFKA_BROKER_URL: 'kafka:9092'
      CONSUMER_GROUP: 'crawlers'
      TOPIC_INPUT: 'ClassifiedDomains'
      TOPIC_OUTPUT: 'ScrapedPages'
      TIMEOUT_POLLING_MS: 10
      MAX_RECORD_POLLING: 5
      MESSAGES_PER_SECOND: 1000
      DEPTH_LIMIT: 8
      DOWLOAND_DELAY: 0.3
      CLOSESPIDER_PAGECOUNT: 25
      AUTOTHROTTLE_ENABLE: 'true'
      AUTOTHROTTLE_TARGET_CONCURRENCY: 10
      TIMEOUT_CRAWLER: 180
      TIMEOUT_DOWNLOAD: '5'
      MONGODB_ADDRESS: "mongodb:27017"
      DATABASE: 'CrawledPages'
    volumes:
      - ./crawler/src:/src
    external_links:
      - mongo

  crawler_10:
    build: ./crawler
    container_name: 'crawler-10'
    environment:
      KAFKA_BROKER_URL: 'kafka:9092'
      CONSUMER_GROUP: 'crawlers'
      TOPIC_INPUT: 'ClassifiedDomains'
      TOPIC_OUTPUT: 'ScrapedPages'
      TIMEOUT_POLLING_MS: 10
      MAX_RECORD_POLLING: 5
      MESSAGES_PER_SECOND: 1000
      DEPTH_LIMIT: 8
      DOWLOAND_DELAY: 0.3
      CLOSESPIDER_PAGECOUNT: 25
      AUTOTHROTTLE_ENABLE: 'true'
      AUTOTHROTTLE_TARGET_CONCURRENCY: 10
      TIMEOUT_CRAWLER: 180
      TIMEOUT_DOWNLOAD: '5'
      MONGODB_ADDRESS: "mongodb:27017"
      DATABASE: 'CrawledPages'
    volumes:
      - ./crawler/src:/src
    external_links:
      - mongo

  shingler:
    build: ./shingler
    container_name: 'shingler'
    environment:
      KAFKA_BROKER_URL: 'kafka:9092'
      TOPIC_INPUT: 'ScrapedPages'
      TIMEOUT_POLLING_MS: 10
      MAX_RECORD_POLLING: 5
      SHINGLE_WINDOW: 3
    volumes:
      - ./shingler/src:/src

networks:
  default:
    external:
      name: environment-network







