version: '3'
services:
  web_discovery:
    build: ./web_discovery
    environment:
      KAFKA_BROKER_URL: kafka:9092
      OUTPUT_TOPIC: DominiTrovati
      MESSAGES_PER_SECOND: 1000
      SEED: './data/products_seed.txt'
      NUMBER_RESULT_PAGES: 3
      SEARX_ADDRESS: 'http://searx:8888'
    volumes:
      - ./web_discovery/data:/data
      - ./web_discovery/src:/src
  classifier:
    build: ./classifier
    environment:
      KAFKA_BROKER_URL: kafka:9092
      TOPIC_INPUT: DominiTrovati
      TOPIC_OUTPUT: DominiClassificati
      MESSAGES_PER_SECOND: 1000
      TRAINING_SET: './data/training_set.csv'
      TRAINING_PARQUET: './data/training_set.snappy.parquet'
      MODEL: './model/classifier.sav'
    volumes:
      - ./classifier/data:/data
      - ./classifier/model:/model
      - ./classifier/src:/src
  crawler:
    build: ./crawler
    environment:
      KAFKA_BROKER_URL: kafka:9092
      TOPIC_INPUT: DominiClassificati
      TOPIC_OUTPUT: DominiClassificati
      MESSAGES_PER_SECOND: 1000
    volumes:
      - ./crawler/data:/data
      - ./crawler/src:/src
networks:
  default:
    external:
      name: environment-network







