version: '3'
services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
  searx:
    image: wonderfall/searx
    ports:
      - 8888:8888
  zookeeper:
      image: wurstmeister/zookeeper
      expose:
        - 2181
      ports:
        - 2181:2181
  kafka:
    image: wurstmeister/kafka:latest
    depends_on:
    - zookeeper
    ports:
    - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://foxlink_kafka_1:9092
      KAFKA_LISTENERS: PLAINTEXT://foxlink_kafka_1:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "DominiTrovati:1:1,DominiClassificati:1:1:compact"
networks:
  default:
    external:
      name: environment-network