version: '3'
services:
  web_discovery:
    build: ./web_discovery
    #command: ["bash", "./wait-for-it.sh", "searx:8888", "--", "python", "main.py"]
    #depends_on:
    #  - searx
    environment:
      KAFKA_BROKER_URL: kafka:9092
      OUTPUT_TOPIC: DominiTrovati
      MESSAGES_PER_SECOND: 1000
  classifier:
    build: ./classifier
    #command: ["bash", "./wait-for-it.sh", "searx:8888", "--", "python", "main.py"]
    environment:
      KAFKA_BROKER_URL: kafka:9092
      TOPIC_INPUT: DominiTrovati
      TOPIC_OUTPUT: DominiClassificati
      MESSAGES_PER_SECOND: 1000
      TRAINING_SET: 'data/training_set.csv'
      TRAINING_PARQUET: 'data/training_set.parquet'
      MODEL: 'classifier.sav'
    volumes:
      - ./classifier/data:/data
      - ./classifier/model:/model
  crawler:
    build: ./crawler
    environment:
      KAFKA_BROKER_URL: kafka:9092
      TOPIC_INPUT: DominiClassificati
      TOPIC_OUTPUT: DominiClassificati
      MESSAGES_PER_SECOND: 1000
networks:
  default:
    external:
      name: environment-network







