version: '3'
services:
  web_discovery:
    build: web_discovery
    #command: ["bash", "./wait-for-it.sh", "searx:8888", "--", "python", "main.py"]
    #depends_on:
    #  - searx
    environment:
      KAFKA_BROKER_URL: foxlink_kafka_1:9092
      TOPIC: DominiTrovati
      MESSAGES_PER_SECOND: 1000
  classifier:
    build: classifier
    #command: ["bash", "./wait-for-it.sh", "searx:8888", "--", "python", "main.py"]
    environment:
      KAFKA_BROKER_URL: foxlink_kafka_1:9092
      TOPIC_INPUT: DominiTrovati
      MESSAGES_PER_SECOND: 1000
networks:
  default:
    external:
      name: environment-network







